// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ┌───────────────────────────────────────────────────────────────────────┐
// │  THIS IS A PLACEHOLDER.                                                 │
// │                                                                        │
// │  The values below are NOT real. Before running the app, connect your   │
// │  own Firebase project by running:                                      │
// │                                                                        │
// │      flutterfire configure                                             │
// │                                                                        │
// │  That command overwrites this file with the real options for your      │
// │  project. See the README ("Firebase setup") for the full steps.        │
// └───────────────────────────────────────────────────────────────────────┘
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVvoJ5P8-fJLu__EFSm1sZ9JLeHAB1lzo',
    appId: '1:10825282583:web:26be3e474697defdc95852',
    messagingSenderId: '10825282583',
    projectId: 'abcd-37a04',
    authDomain: 'abcd-37a04.firebaseapp.com',
    storageBucket: 'abcd-37a04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciM-ftPVPz0ulLoMR3pDJCtrpTqActrk',
    appId: '1:10825282583:android:0ecc5996c762e1adc95852',
    messagingSenderId: '10825282583',
    projectId: 'abcd-37a04',
    storageBucket: 'abcd-37a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTw_8IdTEe2FIHaqklj-exrGv3b-o_zfY',
    appId: '1:10825282583:ios:e8e86749f226c49ac95852',
    messagingSenderId: '10825282583',
    projectId: 'abcd-37a04',
    storageBucket: 'abcd-37a04.firebasestorage.app',
    androidClientId: '10825282583-2qgj2t03ajeslgbmbtg42ka1ivhp4h0v.apps.googleusercontent.com',
    iosClientId: '10825282583-09l1sorki1h82647r1s875672034nh1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTw_8IdTEe2FIHaqklj-exrGv3b-o_zfY',
    appId: '1:10825282583:ios:e8e86749f226c49ac95852',
    messagingSenderId: '10825282583',
    projectId: 'abcd-37a04',
    storageBucket: 'abcd-37a04.firebasestorage.app',
    androidClientId: '10825282583-2qgj2t03ajeslgbmbtg42ka1ivhp4h0v.apps.googleusercontent.com',
    iosClientId: '10825282583-09l1sorki1h82647r1s875672034nh1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4wr8U07Jq25h8qjgTIalX9wgrf7m-tgc',
    appId: '1:10825282583:web:61ce924e10e9ff49c95852',
    messagingSenderId: '10825282583',
    projectId: 'abcd-37a04',
    authDomain: 'abcd-37a04.firebaseapp.com',
    storageBucket: 'abcd-37a04.firebasestorage.app',
  );

}